/** One user-facing sentence per catalog plugin, in every shipped language. */

import type { CatalogModule } from './catalog.ts'

/**
 * Simplified Chinese summary of what each plugin does for the person using the app.
 *
 * Each sentence is derived from that package's own README and `description`, states an
 * observable effect rather than its internal role, and omits engineering vocabulary. The
 * `satisfies` check rejects a missing or surplus key against the catalog.
 */
export const summariesZh = {
  '@deepseek-ai/cordis-plugin-timer'                     : '为其他插件提供定时与延时调度功能',
  '@deepseek-ai/cordis-plugin-hmr'                       : '开发时自动重新加载修改的代码，无需重启',
  '@deepseek-ai/dsh-llm'                                 : '让助手连接外部AI服务以生成回复',
  '@deepseek-ai/dsh-session'                             : '记录并保存对话历史供助手查阅',
  '@deepseek-ai/dsh-typert-registry'                     : '为前后端通信提供内部类型校验支持',
  '@deepseek-ai/dsh-typert-loader'                       : '为插件加载内部类型定义以正常工作',
  '@deepseek-ai/dsh-api-gateway'                         : '在前后端之间传递请求，让功能正常协作',
  '@deepseek-ai/dsh-session-title'                       : '自动为对话命名，方便之后查找',
  '@deepseek-ai/dsh-session-title-first-prompt-llm'      : '用AI根据你的第一条消息生成对话标题',
  '@deepseek-ai/dsh-user-questions'                      : '让助手在需要时暂停并向你提问',
  '@deepseek-ai/dsh-agent'                               : '定义助手如何管理对话与自身行为',
  '@deepseek-ai/dsh-agent-default-model'                 : '设置新对话默认使用的AI模型',
  '@deepseek-ai/dsh-jobs-local'                          : '跟踪助手启动的后台任务，可查看或取消',
  '@deepseek-ai/dsh-llm-retry'                           : '在AI响应失败时自动重试，避免临时故障中断',
  '@deepseek-ai/dsh-settings-file'                       : '将应用设置保存到本地文件以便持久保留',
  '@deepseek-ai/dsh-credentials-local'                   : '在本地保存你的API密钥以便连接AI服务',
  '@deepseek-ai/dsh-llm-pi-ai'                           : '把助手接入OpenAI、Anthropic等多家AI模型服务',
  '@deepseek-ai/dsh-session-persistence-jsonl'           : '把聊天记录压缩保存到磁盘文件',
  '@deepseek-ai/dsh-attachment-local'                    : '把你分享给助手的图片安全保存在本机',
  '@deepseek-ai/dsh-session-query-sqlite'                : '为所有历史会话提供全文搜索',
  '@deepseek-ai/dsh-session-projection'                  : '让待办清单等界面实时跟随对话更新',
  '@deepseek-ai/dsh-session-telemetry-otel'              : '启用遥测后会把原始会话内容发给采集端',
  '@deepseek-ai/dsh-subprocess-local'                    : '负责运行和管理应用的系统命令与终端进程',
  '@deepseek-ai/dsh-sandbox-local'                       : '把命令限制在安全沙盒中防止误改其他文件',
  '@deepseek-ai/dsh-sandbox-policy'                      : '决定本次会话命令可访问文件的范围',
  '@deepseek-ai/dsh-bash-sandbox'                        : '在受限沙盒中运行bash命令并报告被拦截的写入',
  '@deepseek-ai/dsh-pwsh-sandbox'                        : '在受限沙盒中运行PowerShell命令并报告被拦截的写入',
  '@deepseek-ai/dsh-user-approval'                       : '在助手执行风险操作前请你确认批准',
  '@deepseek-ai/dsh-permission-presets'                  : '一键切换写入或完全访问等权限模式',
  '@deepseek-ai/dsh-shell-env'                           : '为bash和PowerShell命令提供所需环境变量',
  '@deepseek-ai/dsh-tool-bash'                           : '让助手运行bash命令并查看输出结果',
  '@deepseek-ai/dsh-tool-pwsh'                           : '让助手运行PowerShell命令并查看输出结果',
  '@deepseek-ai/dsh-tool-jobs'                           : '让助手查看、等待或取消它启动的后台任务',
  '@deepseek-ai/dsh-fs-observation-policy'               : '要求助手先读文件再覆盖或编辑',
  '@deepseek-ai/dsh-tool-fs'                             : '让助手能读取、写入和编辑工作区文件',
  '@deepseek-ai/dsh-tool-fs-search'                      : '让助手能按文件名和内容搜索项目',
  '@deepseek-ai/dsh-agent-instructions'                  : '加载项目的AGENTS.md规则文件，供助手遵循',
  '@deepseek-ai/dsh-skill'                               : '管理助手可加载的技能库',
  '@deepseek-ai/dsh-skill-filesystem'                    : '从本地文件扫描技能，更新可用列表',
  '@deepseek-ai/dsh-skill-badge'                         : '提供现成的\'powered by dsh\'徽章图片和文字',
  '@deepseek-ai/dsh-tool-skill'                          : '让助手查看可用技能并按需加载',
  '@deepseek-ai/dsh-commands'                            : '支持应用中的斜杠指令，如/plan或/feedback',
  '@deepseek-ai/dsh-command-feedback'                    : '把你用/feedback提交的反馈存入会话',
  '@deepseek-ai/dsh-goal'                                : '让助手为会话记录目标并追踪进度',
  '@deepseek-ai/dsh-goal-round-driver'                   : '自动推动助手朝当前目标持续工作',
  '@deepseek-ai/dsh-command-goal'                        : '用/goal命令设置、编辑、暂停或恢复目标',
  '@deepseek-ai/dsh-plan-mode'                           : '让助手先规划再执行，经你确认后再动手',
  '@deepseek-ai/dsh-token-meter'                         : '估算每次请求消耗的token数量，帮助管理上下文',
  '@deepseek-ai/dsh-compaction-basic'                    : '长对话变长时自动生成摘要，节省上下文空间',
  '@deepseek-ai/dsh-command-compact'                     : '输入 /compact 命令手动生成对话摘要',
  '@deepseek-ai/dsh-subagent'                            : '让助手把任务交给其他智能体协助完成',
  '@deepseek-ai/dsh-subagent-spawn-in-process'           : '启动没有当前对话记忆的全新助手代理处理任务',
  '@deepseek-ai/dsh-subagent-fork-in-process'            : '启动已了解目前对话内容的助手代理',
  '@deepseek-ai/dsh-tool-subagent-control'               : '让助手给已启动的助手代理发消息、停止或列出它们',
  '@deepseek-ai/dsh-tool-subagent-control/list-agents'   : '让助手列出正在运行或等待的助手代理',
  '@deepseek-ai/dsh-tool-subagent'                       : '让助手把任务交给助手代理并取回结果',
  '@deepseek-ai/dsh-tool-subagent-report'                : '让后台助手代理把进展回报给启动它的智能体',
  '@deepseek-ai/dsh-workflow-worker-thread'              : '在后台运行自动化脚本，协调多个助手代理',
  '@deepseek-ai/dsh-tool-workflow'                       : '让助手运行自动化脚本调度多个助手代理',
  '@deepseek-ai/dsh-tool-call-timeout-policy'            : '工具调用耗时过长时报错而不是一直等待',
  '@deepseek-ai/dsh-spill-local'                         : '把过大的工具输出保存到本地文件而不放进对话',
  '@deepseek-ai/dsh-spill-policy'                        : '工具结果过长时自动存文件，只显示预览',
  '@deepseek-ai/dsh-session-checkpoint-policy'           : '在安全时机保存对话进度，防止崩溃丢失最新内容',
  '@deepseek-ai/dsh-compaction-tool-result-pruner'       : '自动裁剪工具输出中间内容以控制上下文长度',
  '@deepseek-ai/dsh-tool-todo'                           : '让助手维护并更新任务待办清单',
  '@deepseek-ai/dsh-tool-goal'                           : '让助手创建查看更新长期目标',
  '@deepseek-ai/dsh-tool-ralph'                          : '以固定流程连续派发任务给新助手',
  '@deepseek-ai/dsh-tool-str-replace-editor'             : '让助手查看创建并精确编辑文本文件',
  '@deepseek-ai/dsh-repeat-tool-reminder'                : '提醒助手停止重复相同操作并换个思路',
  '@deepseek-ai/dsh-web'                                 : '为助手提供搜索和访问网页的通道',
  '@deepseek-ai/dsh-web-search-deepseek'                 : '让助手用DeepSeek搜索网页',
  '@deepseek-ai/dsh-tool-web'                            : '让助手搜索网页并获取页面内容',
  '@deepseek-ai/dsh-tools'                               : '运行让助手调用工具的核心流程',
  '@deepseek-ai/dsh-system-prompt'                       : '组装助手每次回复前读取的说明与人设',
  '@deepseek-ai/dsh-agent-loop'                          : '驱动助手思考行动并逐轮作答的核心循环',
  '@deepseek-ai/dsh-fs-sandbox'                          : '把文件修改限制在工作区之内',
  '@deepseek-ai/dsh-llm-deepseek'                        : '让助手连接DeepSeek模型生成回复',
  '@deepseek-ai/dsh-code-runtime-worker-thread'          : '在隔离线程中运行助手编写的代码',
  '@deepseek-ai/dsh-storage'                             : '提供聊天以外应用数据的存储系统',
  '@deepseek-ai/dsh-storage-json'                        : '把应用数据保存为可读JSON文件',
  '@deepseek-ai/dsh-storage-domain'                      : '以校验过的数据表存储工作区等应用数据',
  '@deepseek-ai/dsh-message-feedback'                    : '保存你对某条消息的评分和备注',
  '@deepseek-ai/dsh-session-log-export'                  : '把对话记录连同图片导出为ZIP压缩包',
  '@deepseek-ai/dsh-workspace'                           : '按文件夹将你的会话分组为工作区',
  '@deepseek-ai/dsh-session-projection-cache'            : '缓存摘要加快加载历史会话的速度',
  '@deepseek-ai/dsh-session-stats'                       : '统计每次对话的轮次和用时数据',
  '@deepseek-ai/dsh-host-directory-picker-auto'          : '自动为你的系统选择合适的选文件夹方式',
  '@deepseek-ai/dsh-host-plugin-inventory'               : '支持设置中的插件列表和开关',
  '@deepseek-ai/dsh-host-apiproxy'                       : '负责应用窗口与后台服务之间的所有通信',
  '@deepseek-ai/dsh-cordis-host-runner'                  : '在你批准后运行助手构建的交互组件',
  '@deepseek-ai/dsh-web-app/startup'                     : '启动网页版应用使其准备好提供服务',
  '@deepseek-ai/dsh-host-webserver'                      : '通过HTTP提供网页应用连接',
  '@deepseek-ai/dsh-web-app'                             : '整合浏览器版应用的完整功能',
  '@deepseek-ai/dsh-client-hmr'                          : '开发时自动刷新界面更新内容',
  '@deepseek-ai/dsh-client-modules'                      : '加载并管理组成应用界面的各部分',
  '@deepseek-ai/dsh-client-connection'                   : '让浏览器与后台服务保持实时连接',
  '@deepseek-ai/dsh-api-remotes'                         : '把应用连接到服务端功能，如目标与插件列表',
  '@deepseek-ai/dsh-client-runtime'                      : '让会话和工作区状态保持同步可靠',
  '@deepseek-ai/dsh-cordis-client-runner'                : '在浏览器中运行助手临时创建的插件',
  '@deepseek-ai/dsh-client-ui-theme'                     : '切换应用的浅色、深色或跟随系统外观',
  '@deepseek-ai/dsh-client-locale'                       : '切换应用的中英文界面语言',
  '@deepseek-ai/dsh-client-ui-layout'                    : '排列侧边栏、对话和详情面板，可拖动调整大小',
  '@deepseek-ai/dsh-client-ui-sidebar'                   : '显示侧边栏的标志、新建会话按钮和设置入口',
  '@deepseek-ai/dsh-client-ui-settings'                  : '为设置页面提供保存偏好的底层连接',
  '@deepseek-ai/dsh-client-ui-settings-general'          : '提供设置菜单外壳、通用设置区和首次引导步骤',
  '@deepseek-ai/dsh-client-ui-settings-models'           : '在设置中配置AI模型服务商和API密钥',
  '@deepseek-ai/dsh-client-ui-settings-plugin-inventory' : '显示已安装插件列表，可逐个启用或禁用',
  '@deepseek-ai/dsh-client-ui-conversation'              : '呈现聊天对话、消息输入框和会话标题',
  '@deepseek-ai/dsh-client-ui-tool'                      : '在对话中展示助手的工具操作，如命令和文件编辑',
  '@deepseek-ai/dsh-client-ui-cordis'                    : '显示面板以审批、运行和停止助手创建的插件',
  '@deepseek-ai/dsh-client-ui-workflow-run'              : '以卡片形式展示多步骤工作流的进度',
  '@deepseek-ai/dsh-client-ui-deliverables'              : '在每条回复末尾列出助手创建或修改的文件',
  '@deepseek-ai/dsh-client-ui-workspace'                 : '浏览、搜索并切换工作区及其会话',
  '@deepseek-ai/dsh-client-ui-input-trigger'             : '输入 / 或 @ 时弹出选择菜单',
  '@deepseek-ai/dsh-client-ui-commands'                  : '提供斜杠命令菜单及其弹出选项',
  '@deepseek-ai/dsh-client-ui-skill'                     : '输入/名称调用技能，并显示调用记录',
  '@deepseek-ai/dsh-client-ui-subagent'                  : '显示会话中的子代理，可用 @ 引用',
  '@deepseek-ai/dsh-client-ui-jobs'                      : '在会话中显示后台任务及其状态',
  '@deepseek-ai/dsh-client-ui-goal'                      : '在输入框上方显示并可编辑会话目标',
  '@deepseek-ai/dsh-client-ui-message-feedback'          : '为助手回复添加点赞点踩及备注',
  '@deepseek-ai/dsh-client-ui-model-selection'           : '可为会话选择模型及推理强度',
  '@deepseek-ai/dsh-client-ui-permission-presets'        : '可为新建或当前会话选择权限预设',
  '@deepseek-ai/dsh-client-ui-agent-preset'              : '可选择、复制并管理会话使用的智能体预设',
  '@deepseek-ai/dsh-client-ui-settings-plugins'          : '提供插件设置页面用于配置已安装插件',
  '@deepseek-ai/dsh-client-ui-plan'                      : '显示计划模式提示，可点击关闭',
  '@deepseek-ai/dsh-client-ui-user-questions'            : '显示模型提出的问题及计划审阅供你回答',
  '@deepseek-ai/dsh-client-ui-trajectory'                : '展示会话中每个事件与轮次的详细时间线',
  '@deepseek-ai/dsh-agent-presets'                       : '决定每个智能体预设为助手提供的工具与指令',
} satisfies Record<CatalogModule, string>

/** English summary of each plugin, carrying the same user-facing fact as `summariesZh`. */
export const summariesEn = {
  '@deepseek-ai/cordis-plugin-timer'                     : 'Schedules delayed and repeating internal tasks that other plugins depend on',
  '@deepseek-ai/cordis-plugin-hmr'                       : 'Reloads changed code automatically during development without a full restart',
  '@deepseek-ai/dsh-llm'                                 : 'Connects the assistant to outside AI services so it can generate responses',
  '@deepseek-ai/dsh-session'                             : 'Records and stores your conversation history so the assistant can reference it',
  '@deepseek-ai/dsh-typert-registry'                     : 'Provides internal type definitions that let backend and frontend communicate correctly',
  '@deepseek-ai/dsh-typert-loader'                       : 'Loads internal type definitions needed for the app\'s plugins to work correctly',
  '@deepseek-ai/dsh-api-gateway'                         : 'Routes requests between the app\'s frontend and backend so features work together',
  '@deepseek-ai/dsh-session-title'                       : 'Automatically names your conversations so you can find them later',
  '@deepseek-ai/dsh-session-title-first-prompt-llm'      : 'Uses AI to generate a conversation title from your very first message',
  '@deepseek-ai/dsh-user-questions'                      : 'Lets the assistant pause and ask you a question when it needs your input',
  '@deepseek-ai/dsh-agent'                               : 'Defines how the assistant manages conversations, turns, and its own behavior',
  '@deepseek-ai/dsh-agent-default-model'                 : 'Sets which AI model a new conversation uses by default',
  '@deepseek-ai/dsh-jobs-local'                          : 'Tracks background tasks the assistant starts so you can check or cancel them',
  '@deepseek-ai/dsh-llm-retry'                           : 'Automatically retries a failed AI response so temporary errors don\'t interrupt you',
  '@deepseek-ai/dsh-settings-file'                       : 'Saves your app settings to a file on disk so they persist between sessions',
  '@deepseek-ai/dsh-credentials-local'                   : 'Stores your API keys locally so the assistant can connect to outside AI services',
  '@deepseek-ai/dsh-llm-pi-ai'                           : 'Connects the assistant to OpenAI, Anthropic, DeepSeek and other AI services',
  '@deepseek-ai/dsh-session-persistence-jsonl'           : 'Saves your chat history to disk as compressed session log files',
  '@deepseek-ai/dsh-attachment-local'                    : 'Stores images you share with the assistant safely on your device',
  '@deepseek-ai/dsh-session-query-sqlite'                : 'Powers fast full-text search across all your past chat sessions',
  '@deepseek-ai/dsh-session-projection'                  : 'Keeps live views like your todo list in sync with the conversation',
  '@deepseek-ai/dsh-session-telemetry-otel'              : 'When enabled, shares raw session content with the telemetry collector',
  '@deepseek-ai/dsh-subprocess-local'                    : 'Runs and manages system commands and terminal processes for the app',
  '@deepseek-ai/dsh-sandbox-local'                       : 'Confines commands to a safe sandbox so they can\'t touch other files',
  '@deepseek-ai/dsh-sandbox-policy'                      : 'Decides how much file access commands are allowed for this session',
  '@deepseek-ai/dsh-bash-sandbox'                        : 'Runs bash commands inside a confined sandbox and reports blocked writes',
  '@deepseek-ai/dsh-pwsh-sandbox'                        : 'Runs PowerShell commands inside a confined sandbox and reports blocked writes',
  '@deepseek-ai/dsh-user-approval'                       : 'Asks you to approve risky actions before the assistant carries them out',
  '@deepseek-ai/dsh-permission-presets'                  : 'Lets you switch between permission modes like write access and full access',
  '@deepseek-ai/dsh-shell-env'                           : 'Supplies bash and PowerShell commands with the environment variables they need',
  '@deepseek-ai/dsh-tool-bash'                           : 'Lets the assistant run bash commands and see their output',
  '@deepseek-ai/dsh-tool-pwsh'                           : 'Lets the assistant run PowerShell commands and see their output',
  '@deepseek-ai/dsh-tool-jobs'                           : 'Lets the assistant check on, wait for, or cancel background jobs it started',
  '@deepseek-ai/dsh-fs-observation-policy'               : 'Requires the assistant to read a file before it can overwrite or edit it',
  '@deepseek-ai/dsh-tool-fs'                             : 'Gives the assistant tools to read, write, and edit files in your workspace',
  '@deepseek-ai/dsh-tool-fs-search'                      : 'Gives the assistant tools to search file names and file contents in your project',
  '@deepseek-ai/dsh-agent-instructions'                  : 'Reads your project\'s AGENTS.md/CLAUDE.md files so the assistant follows your rules',
  '@deepseek-ai/dsh-skill'                               : 'Manages the library of skills the assistant can load for specialized tasks',
  '@deepseek-ai/dsh-skill-filesystem'                    : 'Finds skill files on disk so the assistant\'s skill list stays up to date',
  '@deepseek-ai/dsh-skill-badge'                         : 'Adds an optional skill that provides ready-made \'powered by dsh\' badge images and text',
  '@deepseek-ai/dsh-tool-skill'                          : 'Shows the assistant which skills are available and lets it load one when relevant',
  '@deepseek-ai/dsh-commands'                            : 'Runs the slash commands users type in the app, like /plan or /feedback',
  '@deepseek-ai/dsh-command-feedback'                    : 'Records feedback you submit with /feedback so it\'s saved to the session',
  '@deepseek-ai/dsh-goal'                                : 'Lets the assistant track a session goal and remember progress toward it',
  '@deepseek-ai/dsh-goal-round-driver'                   : 'Automatically keeps the assistant working toward the current goal without extra prompts',
  '@deepseek-ai/dsh-command-goal'                        : 'Lets you set, edit, pause, or resume the session goal with the /goal command',
  '@deepseek-ai/dsh-plan-mode'                           : 'Adds a plan mode where the assistant explores and proposes a plan before you approve it',
  '@deepseek-ai/dsh-token-meter'                         : 'Estimates how many tokens each request uses so the assistant can manage context size',
  '@deepseek-ai/dsh-compaction-basic'                    : 'Automatically condenses older conversation history into a summary to free up space',
  '@deepseek-ai/dsh-command-compact'                     : 'Lets you manually trigger a conversation summary with a /compact command',
  '@deepseek-ai/dsh-subagent'                            : 'Lets the assistant delegate tasks to helper agents that work in the background',
  '@deepseek-ai/dsh-subagent-spawn-in-process'           : 'Starts a fresh helper agent with no memory of the conversation to handle a task',
  '@deepseek-ai/dsh-subagent-fork-in-process'            : 'Starts a helper agent that already knows everything said so far in the conversation',
  '@deepseek-ai/dsh-tool-subagent-control'               : 'Lets the assistant message, stop, or list background helper agents it started',
  '@deepseek-ai/dsh-tool-subagent-control/list-agents'   : 'Lets the assistant list the background helper agents currently running or waiting',
  '@deepseek-ai/dsh-tool-subagent'                       : 'Lets the assistant hand off a task to a helper agent and get back its answer',
  '@deepseek-ai/dsh-tool-subagent-report'                : 'Lets a background helper agent send an update back to the agent that started it',
  '@deepseek-ai/dsh-workflow-worker-thread'              : 'Runs multi-step automation scripts that coordinate many helper agents at once',
  '@deepseek-ai/dsh-tool-workflow'                       : 'Lets the assistant run a scripted workflow that manages many helper agents together',
  '@deepseek-ai/dsh-tool-call-timeout-policy'            : 'Stops a tool call that takes too long and reports a timeout instead of hanging',
  '@deepseek-ai/dsh-spill-local'                         : 'Saves oversized tool output to a local file instead of keeping it in the chat',
  '@deepseek-ai/dsh-spill-policy'                        : 'Automatically saves overly long tool results to a file and shows a short preview instead',
  '@deepseek-ai/dsh-session-checkpoint-policy'           : 'Saves your conversation progress at safe points so a crash doesn\'t lose recent work',
  '@deepseek-ai/dsh-compaction-tool-result-pruner'       : 'Trims the middle of long tool outputs to keep conversations under the memory limit',
  '@deepseek-ai/dsh-tool-todo'                           : 'Lets the assistant keep and update a running to-do list for your task',
  '@deepseek-ai/dsh-tool-goal'                           : 'Lets the assistant create, check, and update one long-running goal',
  '@deepseek-ai/dsh-tool-ralph'                          : 'Runs a repeating workflow that hands one task to fresh AI helpers in turn',
  '@deepseek-ai/dsh-tool-str-replace-editor'             : 'Lets the assistant view, create, and precisely edit text files',
  '@deepseek-ai/dsh-repeat-tool-reminder'                : 'Nudges the assistant to stop repeating the same action and try something else',
  '@deepseek-ai/dsh-web'                                 : 'Provides the shared connection that lets the assistant search and fetch web pages',
  '@deepseek-ai/dsh-web-search-deepseek'                 : 'Lets the assistant search the web using DeepSeek\'s own search model',
  '@deepseek-ai/dsh-tool-web'                            : 'Lets the assistant search the web and fetch page content on request',
  '@deepseek-ai/dsh-tools'                               : 'Runs the pipeline that lets the assistant call tools like search, files, and web',
  '@deepseek-ai/dsh-system-prompt'                       : 'Assembles the instructions and persona the assistant reads before every reply',
  '@deepseek-ai/dsh-agent-loop'                          : 'Drives the core loop that lets the assistant think, act, and respond in turns',
  '@deepseek-ai/dsh-fs-sandbox'                          : 'Confines file edits to your workspace so the assistant can\'t write outside it',
  '@deepseek-ai/dsh-llm-deepseek'                        : 'Connects the assistant to DeepSeek\'s chat models to generate replies',
  '@deepseek-ai/dsh-code-runtime-worker-thread'          : 'Runs assistant-written code in an isolated background thread',
  '@deepseek-ai/dsh-storage'                             : 'Provides the shared system that stores app data outside of chat sessions',
  '@deepseek-ai/dsh-storage-json'                        : 'Saves app data as readable JSON files on disk',
  '@deepseek-ai/dsh-storage-domain'                      : 'Stores app data such as workspaces in validated, durable data tables',
  '@deepseek-ai/dsh-message-feedback'                    : 'Saves your rating and optional note on an assistant message',
  '@deepseek-ai/dsh-session-log-export'                  : 'Lets you download a chat\'s full log, including images, as a ZIP file',
  '@deepseek-ai/dsh-workspace'                           : 'Organizes your chat sessions into folders called workspaces',
  '@deepseek-ai/dsh-session-projection-cache'            : 'Speeds up opening past chats by caching summaries instead of full replays',
  '@deepseek-ai/dsh-session-stats'                       : 'Powers the turn counts and response-time stats shown for each chat',
  '@deepseek-ai/dsh-host-directory-picker-auto'          : 'Automatically picks the right folder-browsing method for your setup',
  '@deepseek-ai/dsh-host-plugin-inventory'               : 'Powers the plugin list and on/off switches in Settings',
  '@deepseek-ai/dsh-host-apiproxy'                       : 'Carries every request between the app window and its background service',
  '@deepseek-ai/dsh-cordis-host-runner'                  : 'Runs interactive components the assistant builds, after you approve them',
  '@deepseek-ai/dsh-web-app/startup'                     : 'Starts up the web app and gets it ready to serve your browser',
  '@deepseek-ai/dsh-host-webserver'                      : 'Serves the web app over HTTP so your browser can connect to it',
  '@deepseek-ai/dsh-web-app'                             : 'Assembles the whole browser-based version of the app',
  '@deepseek-ai/dsh-client-hmr'                          : 'Refreshes updated interface parts automatically while developers are working',
  '@deepseek-ai/dsh-client-modules'                      : 'Loads and organizes the interface pieces that make up the app screen',
  '@deepseek-ai/dsh-client-connection'                   : 'Keeps your browser connected live to the app\'s background service',
  '@deepseek-ai/dsh-api-remotes'                         : 'Connects the app to server-side features like the goal tracker and the plugin list',
  '@deepseek-ai/dsh-client-runtime'                      : 'Keeps sessions and workspaces in sync so switching between chats stays reliable',
  '@deepseek-ai/dsh-cordis-client-runner'                : 'Loads and runs plugins the assistant creates on the fly directly in your browser',
  '@deepseek-ai/dsh-client-ui-theme'                     : 'Lets you switch the app between light, dark, and system appearance',
  '@deepseek-ai/dsh-client-locale'                       : 'Lets you switch the app\'s language between Chinese and English',
  '@deepseek-ai/dsh-client-ui-layout'                    : 'Arranges the sidebar, chat, and details panels and lets you resize them',
  '@deepseek-ai/dsh-client-ui-sidebar'                   : 'Shows the sidebar with the app logo, new chat button, and settings shortcut',
  '@deepseek-ai/dsh-client-ui-settings'                  : 'Provides the connection that lets Settings pages read and save your preferences',
  '@deepseek-ai/dsh-client-ui-settings-general'          : 'Provides the Settings menu shell, General section, and first-run onboarding steps',
  '@deepseek-ai/dsh-client-ui-settings-models'           : 'Lets you configure AI models and API keys in Settings',
  '@deepseek-ai/dsh-client-ui-settings-plugin-inventory' : 'Shows the list of installed plugins and lets you enable or disable each one',
  '@deepseek-ai/dsh-client-ui-conversation'              : 'Renders the chat conversation, message composer, and session header',
  '@deepseek-ai/dsh-client-ui-tool'                      : 'Shows the assistant\'s tool actions like commands and file edits in the chat',
  '@deepseek-ai/dsh-client-ui-cordis'                    : 'Shows a panel to approve, run, and stop plugins the assistant creates',
  '@deepseek-ai/dsh-client-ui-workflow-run'              : 'Shows the progress of multi-step workflow runs as cards in the chat',
  '@deepseek-ai/dsh-client-ui-deliverables'              : 'Lists the files the assistant created or edited at the end of each reply',
  '@deepseek-ai/dsh-client-ui-workspace'                 : 'Lets you browse, search, and switch between workspaces and their sessions',
  '@deepseek-ai/dsh-client-ui-input-trigger'             : 'Shows a pop-up menu when you type / or @ in the message box',
  '@deepseek-ai/dsh-client-ui-commands'                  : 'Powers the slash-command menu and its option pop-ups in the message box',
  '@deepseek-ai/dsh-client-ui-skill'                     : 'Lets you invoke skills by typing /name and shows the call in the chat',
  '@deepseek-ai/dsh-client-ui-subagent'                  : 'Shows a session\'s subagent conversations and lets you reference them with @',
  '@deepseek-ai/dsh-client-ui-jobs'                      : 'Lists background jobs running in the current session with their status',
  '@deepseek-ai/dsh-client-ui-goal'                      : 'Shows the session\'s current goal above the message box and lets you edit it',
  '@deepseek-ai/dsh-client-ui-message-feedback'          : 'Adds Like and Dislike buttons with notes to assistant replies',
  '@deepseek-ai/dsh-client-ui-model-selection'           : 'Lets you pick the model and reasoning effort for the session',
  '@deepseek-ai/dsh-client-ui-permission-presets'        : 'Lets you choose the permission preset for new or current sessions',
  '@deepseek-ai/dsh-client-ui-agent-preset'              : 'Lets you choose, copy, and manage the agent presets sessions are built from',
  '@deepseek-ai/dsh-client-ui-settings-plugins'          : 'Adds the Plugins settings page for configuring installed plugins',
  '@deepseek-ai/dsh-client-ui-plan'                      : 'Shows a Plan Mode indicator you can tap to turn planning off',
  '@deepseek-ai/dsh-client-ui-user-questions'            : 'Shows the model\'s questions and plan reviews for you to answer',
  '@deepseek-ai/dsh-client-ui-trajectory'                : 'Shows a detailed timeline of every event and turn in the session',
  '@deepseek-ai/dsh-agent-presets'                       : 'Defines which tools and instructions each agent preset gives the assistant',
} satisfies Record<CatalogModule, string>

/**
 * Brazilian Portuguese summary of what each plugin does for the person using
 * the app, mirrored from the English sentence it ports. `pt` is the
 * incrementally translated language; the same `satisfies` check keeps every
 * key aligned with the catalog, and namespaces without `pt` fall back to `en`
 * at lookup time.
 */
export const summariesPt = {
  '@deepseek-ai/cordis-plugin-timer'                    : 'Agenda tarefas internas atrasadas e repetidas das quais outros plugins dependem',
  '@deepseek-ai/cordis-plugin-hmr'                      : 'Recarrega código alterado automaticamente durante o desenvolvimento, sem reiniciar tudo',
  '@deepseek-ai/dsh-llm'                                : 'Conecta o assistente a serviços externos de IA para que ele gere respostas',
  '@deepseek-ai/dsh-session'                            : 'Grava e armazena seu histórico de conversas para o assistente consultar',
  '@deepseek-ai/dsh-typert-registry'                    : 'Fornece definições de tipo internas que fazem backend e frontend se comunicarem',
  '@deepseek-ai/dsh-typert-loader'                      : 'Carrega definições de tipo internas necessárias para os plugins do app funcionarem',
  '@deepseek-ai/dsh-api-gateway'                        : 'Roteia requisições entre o frontend e o backend do app para os recursos funcionarem',
  '@deepseek-ai/dsh-session-title'                      : 'Nomeia suas conversas automaticamente para você encontrá-las depois',
  '@deepseek-ai/dsh-session-title-first-prompt-llm'     : 'Usa IA para gerar um título de conversa a partir da sua primeira mensagem',
  '@deepseek-ai/dsh-user-questions'                     : 'Permite que o assistente pause e pergunte algo quando precisar de você',
  '@deepseek-ai/dsh-agent'                              : 'Define como o assistente gerencia conversas, turnos e o próprio comportamento',
  '@deepseek-ai/dsh-agent-default-model'                : 'Define qual modelo de IA uma nova conversa usa por padrão',
  '@deepseek-ai/dsh-jobs-local'                         : 'Acompanha tarefas em segundo plano do assistente para conferir ou cancelar',
  '@deepseek-ai/dsh-llm-retry'                          : 'Repete automaticamente respostas de IA com falha para erros temporários não interromperem',
  '@deepseek-ai/dsh-settings-file'                      : 'Salva suas configurações do app em um arquivo no disco para persistirem entre sessões',
  '@deepseek-ai/dsh-credentials-local'                  : 'Guarda suas chaves de API no dispositivo para o assistente acessar serviços externos de IA',
  '@deepseek-ai/dsh-llm-pi-ai'                          : 'Conecta o assistente a OpenAI, Anthropic, DeepSeek e outros serviços de IA',
  '@deepseek-ai/dsh-session-persistence-jsonl'          : 'Salva seu histórico de conversas no disco como arquivos de log compactados',
  '@deepseek-ai/dsh-attachment-local'                   : 'Armazena com segurança no seu dispositivo as imagens que você compartilha com o assistente',
  '@deepseek-ai/dsh-session-query-sqlite'               : 'Permite busca rápida por texto em todas as suas conversas passadas',
  '@deepseek-ai/dsh-session-projection'                 : 'Mantém visões ao vivo, como sua lista de tarefas, sincronizadas com a conversa',
  '@deepseek-ai/dsh-session-telemetry-otel'             : 'Quando ativado, compartilha o conteúdo bruto da sessão com o coletor de telemetria',
  '@deepseek-ai/dsh-subprocess-local'                   : 'Executa e gerencia comandos do sistema e processos de terminal do aplicativo',
  '@deepseek-ai/dsh-sandbox-local'                      : 'Isola comandos num sandbox seguro para não afetarem outros arquivos',
  '@deepseek-ai/dsh-sandbox-policy'                     : 'Decide qual nível de acesso a arquivos os comandos têm nesta sessão',
  '@deepseek-ai/dsh-bash-sandbox'                       : 'Executa comandos bash num sandbox confinado e reporta gravações bloqueadas',
  '@deepseek-ai/dsh-pwsh-sandbox'                       : 'Executa comandos PowerShell num sandbox confinado e reporta gravações bloqueadas',
  '@deepseek-ai/dsh-user-approval'                      : 'Pede sua aprovação para ações arriscadas antes de o assistente executá-las',
  '@deepseek-ai/dsh-permission-presets'                 : 'Permite alternar entre modos de permissão, como gravação e acesso total',
  '@deepseek-ai/dsh-shell-env'                          : 'Fornece aos comandos bash e PowerShell as variáveis de ambiente de que precisam',
  '@deepseek-ai/dsh-tool-bash'                          : 'Deixa o assistente executar comandos bash e ver a saída deles',
  '@deepseek-ai/dsh-tool-pwsh'                          : 'Deixa o assistente executar comandos PowerShell e ver a saída deles',
  '@deepseek-ai/dsh-tool-jobs'                          : 'Permite ao assistente conferir, aguardar ou cancelar tarefas em segundo plano',
  '@deepseek-ai/dsh-fs-observation-policy'              : 'Exige que o assistente leia um arquivo antes de sobrescrevê-lo ou editá-lo',
  '@deepseek-ai/dsh-tool-fs'                            : 'Dá ao assistente ferramentas para ler, escrever e editar arquivos no seu projeto',
  '@deepseek-ai/dsh-tool-fs-search'                     : 'Dá ao assistente ferramentas para pesquisar nomes e conteúdos de arquivos no seu projeto',
  '@deepseek-ai/dsh-agent-instructions'                 : 'Lê os arquivos AGENTS.md/CLAUDE.md do seu projeto para que o assistente siga suas regras',
  '@deepseek-ai/dsh-skill'                              : 'Gerencia as habilidades que o assistente pode usar em tarefas especializadas',
  '@deepseek-ai/dsh-skill-filesystem'                   : 'Encontra arquivos de habilidade no disco para que a lista do assistente fique atualizada',
  '@deepseek-ai/dsh-skill-badge'                        : 'Adiciona uma habilidade opcional com imagens e textos prontos da marca \'powered by dsh\'',
  '@deepseek-ai/dsh-tool-skill'                         : 'Mostra ao assistente as habilidades disponíveis e deixa carregar uma quando for relevante',
  '@deepseek-ai/dsh-commands'                           : 'Executa os comandos de barra que os usuários digitam no app, como /plan ou /feedback',
  '@deepseek-ai/dsh-command-feedback'                   : 'Registra o feedback enviado com /feedback para que fique salvo na sessão',
  '@deepseek-ai/dsh-goal'                               : 'Permite ao assistente acompanhar a meta da sessão e lembrar seu progresso',
  '@deepseek-ai/dsh-goal-round-driver'                  : 'Mantém automaticamente o assistente trabalhando na meta atual sem prompts extras',
  '@deepseek-ai/dsh-command-goal'                       : 'Permite definir, editar, pausar ou retomar a meta da sessão com o comando /goal',
  '@deepseek-ai/dsh-plan-mode'                          : 'Adiciona o modo de plano, em que o assistente explora e propõe um plano para sua aprovação',
  '@deepseek-ai/dsh-token-meter'                        : 'Estima quantos tokens cada solicitação usa para o assistente gerenciar o contexto',
  '@deepseek-ai/dsh-compaction-basic'                   : 'Compacta automaticamente o histórico antigo da conversa em um resumo para liberar espaço',
  '@deepseek-ai/dsh-command-compact'                    : 'Deixa você iniciar um resumo da conversa manualmente com o comando /compact',
  '@deepseek-ai/dsh-subagent'                           : 'Deixa o assistente delegar tarefas a agentes auxiliares que trabalham em segundo plano',
  '@deepseek-ai/dsh-subagent-spawn-in-process'          : 'Inicia um agente auxiliar novo, sem memória da conversa, para resolver uma tarefa',
  '@deepseek-ai/dsh-subagent-fork-in-process'           : 'Inicia um agente auxiliar que já sabe tudo que foi dito na conversa até aqui',
  '@deepseek-ai/dsh-tool-subagent-control'              : 'Deixa o assistente enviar mensagem, parar ou listar os agentes auxiliares que iniciou',
  '@deepseek-ai/dsh-tool-subagent-control/list-agents'  : 'Deixa o assistente listar os agentes auxiliares em execução ou aguardando',
  '@deepseek-ai/dsh-tool-subagent'                      : 'Deixa o assistente entregar uma tarefa a um agente auxiliar e receber a resposta',
  '@deepseek-ai/dsh-tool-subagent-report'               : 'Deixa um agente auxiliar enviar uma atualização de volta ao agente que o iniciou',
  '@deepseek-ai/dsh-workflow-worker-thread'             : 'Roda automações com várias etapas que coordenam muitos agentes auxiliares ao mesmo tempo',
  '@deepseek-ai/dsh-tool-workflow'                      : 'Deixa o assistente rodar um fluxo programado que coordena vários agentes auxiliares',
  '@deepseek-ai/dsh-tool-call-timeout-policy'           : 'Interrompe uma chamada de ferramenta demorada e reporta timeout em vez de travar',
  '@deepseek-ai/dsh-spill-local'                        : 'Salva a saída muito grande de uma ferramenta em arquivo local em vez de mantê-la no chat',
  '@deepseek-ai/dsh-spill-policy'                       : 'Salva automaticamente resultados longos de ferramenta em arquivo e mostra uma prévia curta',
  '@deepseek-ai/dsh-session-checkpoint-policy'          : 'Salva o progresso da conversa em pontos seguros para um erro não apagar o recente',
  '@deepseek-ai/dsh-compaction-tool-result-pruner'      : 'Corta o meio de saídas longas de ferramenta para caber no limite de memória',
  '@deepseek-ai/dsh-tool-todo'                          : 'Deixa o assistente manter e atualizar uma lista de tarefas em andamento para a sua tarefa',
  '@deepseek-ai/dsh-tool-goal'                          : 'Deixa o assistente criar, conferir e atualizar uma meta de longo prazo',
  '@deepseek-ai/dsh-tool-ralph'                         : 'Executa um fluxo repetitivo que entrega uma tarefa a novos ajudantes de IA em sequência',
  '@deepseek-ai/dsh-tool-str-replace-editor'            : 'Deixa o assistente ver, criar e editar arquivos de texto com precisão',
  '@deepseek-ai/dsh-repeat-tool-reminder'               : 'Alerta o assistente para parar de repetir a mesma ação e tentar outra coisa',
  '@deepseek-ai/dsh-web'                                : 'Oferece a conexão compartilhada para o assistente pesquisar e buscar páginas da web',
  '@deepseek-ai/dsh-web-search-deepseek'                : 'Deixa o assistente pesquisar na web usando o próprio modelo de busca da DeepSeek',
  '@deepseek-ai/dsh-tool-web'                           : 'Deixa o assistente pesquisar na web e buscar o conteúdo de páginas quando solicitado',
  '@deepseek-ai/dsh-tools'                              : 'Executa o mecanismo que permite ao assistente usar ferramentas como busca, arquivos e web',
  '@deepseek-ai/dsh-system-prompt'                      : 'Reúne as instruções e a persona que o assistente lê antes de cada resposta',
  '@deepseek-ai/dsh-agent-loop'                         : 'Conduz o ciclo principal que permite ao assistente pensar, agir e responder em turnos',
  '@deepseek-ai/dsh-fs-sandbox'                         : 'Limita as edições de arquivos ao seu espaço de trabalho para não gravar fora dele',
  '@deepseek-ai/dsh-llm-deepseek'                       : 'Conecta o assistente aos modelos de chat da DeepSeek para gerar respostas',
  '@deepseek-ai/dsh-code-runtime-worker-thread'         : 'Executa código escrito pelo assistente em uma thread isolada em segundo plano',
  '@deepseek-ai/dsh-storage'                            : 'Oferece o sistema compartilhado que armazena dados do app fora das sessões de chat',
  '@deepseek-ai/dsh-storage-json'                       : 'Salva dados do app como arquivos JSON legíveis no disco',
  '@deepseek-ai/dsh-storage-domain'                     : 'Armazena dados do app, como workspaces, em tabelas validadas e duráveis',
  '@deepseek-ai/dsh-message-feedback'                   : 'Salva sua avaliação e um comentário opcional em uma mensagem do assistente',
  '@deepseek-ai/dsh-session-log-export'                 : 'Baixa o registro completo de um chat, incluindo imagens, em arquivo ZIP',
  '@deepseek-ai/dsh-workspace'                          : 'Organiza suas conversas em pastas chamadas workspaces',
  '@deepseek-ai/dsh-session-projection-cache'           : 'Acelera a abertura de chats antigos guardando resumos em vez de gravações completas',
  '@deepseek-ai/dsh-session-stats'                      : 'Alimenta os contadores de turnos e o tempo de resposta exibidos em cada chat',
  '@deepseek-ai/dsh-host-directory-picker-auto'         : 'Escolhe automaticamente o melhor método de navegação de pastas para o seu sistema',
  '@deepseek-ai/dsh-host-plugin-inventory'              : 'Alimenta a lista de plugins e os interruptores liga/desliga nas Configurações',
  '@deepseek-ai/dsh-host-apiproxy'                      : 'Transporta todas as solicitações entre a janela do app e o serviço em segundo plano',
  '@deepseek-ai/dsh-cordis-host-runner'                 : 'Executa componentes interativos criados pelo assistente, após sua aprovação',
  '@deepseek-ai/dsh-web-app/startup'                    : 'Inicia o app web e o deixa pronto para atender seu navegador',
  '@deepseek-ai/dsh-host-webserver'                     : 'Disponibiliza o app web via HTTP para seu navegador se conectar',
  '@deepseek-ai/dsh-web-app'                            : 'Monta a versão inteira do app baseada no navegador',
  '@deepseek-ai/dsh-client-hmr'                         : 'Atualiza automaticamente partes da interface enquanto os desenvolvedores trabalham',
  '@deepseek-ai/dsh-client-modules'                     : 'Carrega e organiza as peças da interface que formam a tela do app',
  '@deepseek-ai/dsh-client-connection'                  : 'Mantém seu navegador conectado em tempo real ao serviço em segundo plano do app',
  '@deepseek-ai/dsh-api-remotes'                        : 'Conecta o app a recursos no servidor, como o rastreador de metas e a lista de plugins',
  '@deepseek-ai/dsh-client-runtime'                     : 'Mantém sessões e espaços de trabalho em sincronia para tornar trocar de chat confiável',
  '@deepseek-ai/dsh-cordis-client-runner'               : 'Carrega e roda plugins que o assistente cria na hora, direto no seu navegador',
  '@deepseek-ai/dsh-client-ui-theme'                    : 'Permite alternar o app entre aparência clara, escura e do sistema',
  '@deepseek-ai/dsh-client-locale'                      : 'Permite alternar o idioma do app entre chinês e inglês',
  '@deepseek-ai/dsh-client-ui-layout'                   : 'Organiza a barra lateral, o chat e os painéis de detalhes e permite redimensioná-los',
  '@deepseek-ai/dsh-client-ui-sidebar'                  : 'Mostra a barra lateral com o logo do app, o botão novo chat e o atalho de configurações',
  '@deepseek-ai/dsh-client-ui-settings'                 : 'Fornece a conexão que permite às páginas de Configurações ler e salvar suas preferências',
  '@deepseek-ai/dsh-client-ui-settings-general'         : 'Fornece o menu de Configurações, a seção Geral e os passos de primeiro acesso',
  '@deepseek-ai/dsh-client-ui-settings-models'          : 'Permite configurar modelos de IA e chaves de API nas Configurações',
  '@deepseek-ai/dsh-client-ui-settings-plugin-inventory': 'Mostra a lista de plugins instalados e permite ativar ou desativar cada um',
  '@deepseek-ai/dsh-client-ui-conversation'             : 'Renderiza a conversa do chat, o campo de mensagem e o cabeçalho da sessão',
  '@deepseek-ai/dsh-client-ui-tool'                     : 'Mostra as ações de ferramenta do assistente, como comandos e edições de arquivo, no chat',
  '@deepseek-ai/dsh-client-ui-cordis'                   : 'Mostra um painel para aprovar, executar e parar plugins criados pelo assistente',
  '@deepseek-ai/dsh-client-ui-workflow-run'             : 'Mostra o progresso de fluxos de trabalho multi-etapas como cartões no chat',
  '@deepseek-ai/dsh-client-ui-deliverables'             : 'Lista os arquivos que o assistente criou ou editou ao final de cada resposta',
  '@deepseek-ai/dsh-client-ui-workspace'                : 'Deixa você navegar, buscar e trocar entre workspaces e suas sessões',
  '@deepseek-ai/dsh-client-ui-input-trigger'            : 'Mostra um menu pop-up quando você digita / ou @ na caixa de mensagem',
  '@deepseek-ai/dsh-client-ui-commands'                 : 'Alimenta o menu de slash-commands e seus pop-ups de opções na caixa de mensagem',
  '@deepseek-ai/dsh-client-ui-skill'                    : 'Deixa você invocar skills digitando /nome e mostra a chamada no chat',
  '@deepseek-ai/dsh-client-ui-subagent'                 : 'Mostra as conversas de subagente da sessão e deixa você referenciá-las com @',
  '@deepseek-ai/dsh-client-ui-jobs'                     : 'Lista os jobs em segundo plano da sessão atual com seu status',
  '@deepseek-ai/dsh-client-ui-goal'                     : 'Mostra o objetivo atual da sessão acima da caixa de mensagem e deixa você editá-lo',
  '@deepseek-ai/dsh-client-ui-message-feedback'         : 'Adiciona botões Curtir e Não curtir com notas às respostas do assistente',
  '@deepseek-ai/dsh-client-ui-model-selection'          : 'Deixa você escolher o modelo e o esforço de raciocínio para a sessão',
  '@deepseek-ai/dsh-client-ui-permission-presets'       : 'Deixa você escolher o preset de permissão para sessões novas ou atuais',
  '@deepseek-ai/dsh-client-ui-agent-preset'             : 'Deixa você escolher, copiar e gerenciar presets de agente para criar sessões',
  '@deepseek-ai/dsh-client-ui-settings-plugins'         : 'Adiciona a página de configurações de Plugins para configurar os plugins instalados',
  '@deepseek-ai/dsh-client-ui-plan'                     : 'Mostra um indicador de Modo Plano que você pode tocar para desligar o planejamento',
  '@deepseek-ai/dsh-client-ui-user-questions'           : 'Mostra as perguntas do modelo e revisões de plano para você responder',
  '@deepseek-ai/dsh-client-ui-trajectory'               : 'Mostra uma linha do tempo detalhada de cada evento e turno da sessão',
  '@deepseek-ai/dsh-agent-presets'                      : 'Define quais ferramentas e instruções cada preset de agente dá ao assistente',
} satisfies Record<CatalogModule, string>
