/**
 * Measured, locked coverage debt.
 *
 * One entry per debt FILE, with its measured real coverage (lines/statements/
 * branches/functions percentages) as the LOCKED ceiling. The main coverage gate
 * keeps these files excluded from the global perFile:100 (a glob threshold does
 * NOT exempt a file from the global threshold), so they cannot sit in the 100%
 * gate at their current sub-100 values. Instead they are measured and locked by
 * the coverage-debt lane (see verify-coverage-debt.ts):
 *
 *   - real coverage BELOW the locked value  -> the debt lane's per-file glob
 *     threshold fails (vitest), naming the file.
 *   - real coverage ABOVE the locked value  -> verify-coverage-debt.ts fails,
 *     demanding the locked value be raised by reviewed edit (ratchet).
 *   - real coverage == 100                  -> verify-coverage-debt.ts fails,
 *     demanding the entry be DELETED (file returns to the global 100% regime).
 *
 * Raise a value only by raising it in the measured run and committing the new
 * number; never autoUpdate. This table is the single source of truth consumed by
 * both vitest.config.ts (debt lane + main exclude) and verify-coverage-debt.ts,
 * so the main gate and the ratchet cannot drift.
 */

/** One debt file: its glob and the locked real-coverage ceiling for each metric. */
export interface CoverageDebtEntry {
  /** Coverage-relative glob selecting exactly one source file. */
  readonly glob: string
  readonly lines: number
  readonly statements: number
  readonly branches: number
  readonly functions: number
}

/**
 * Sorted by glob. Values are the MEASURED real coverage of each file at the
 * commit that locked them. Update by re-running the debt lane and committing the
 * new numbers (ratchet: only upward, or delete at 100).
 */
export const coverageDebt: readonly CoverageDebtEntry[] = [
  { glob: 'packages/client/connection/src/client/fixture.ts', lines: 83.84, statements: 83.03, branches: 70.89, functions: 82.01 },
  { glob: 'packages/client/connection/src/http-bridge.ts', lines: 63.88, statements: 64.86, branches: 76.92, functions: 50 },
  { glob: 'packages/client/connection/src/index.ts', lines: 97.72, statements: 94.44, branches: 89.28, functions: 83.33 },
  { glob: 'packages/client/hmr/src/client/index.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/hmr/src/index.ts', lines: 77.63, statements: 74.11, branches: 57.14, functions: 64.28 },
  { glob: 'packages/client/hmr/src/invariant.ts', lines: 45, statements: 43.47, branches: 12.5, functions: 60 },
  { glob: 'packages/client/modules/src/client/index.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/modules/src/client/manifest.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/modules/src/index.ts', lines: 66.45, statements: 62.23, branches: 56.25, functions: 70.58 },
  { glob: 'packages/client/modules/src/invariant.ts', lines: 75, statements: 76.92, branches: 25, functions: 100 },
  { glob: 'packages/client/runtime/src/client/contract/context-provenance.ts', lines: 100, statements: 100, branches: 97.72, functions: 100 },
  { glob: 'packages/client/runtime/src/client/contract/notifier.ts', lines: 100, statements: 97.95, branches: 94.44, functions: 100 },
  { glob: 'packages/client/runtime/src/client/contract/store.ts', lines: 96.49, statements: 95.83, branches: 96.55, functions: 100 },
  { glob: 'packages/client/runtime/src/client/conversation/definition-registry.ts', lines: 100, statements: 95.65, branches: 75, functions: 100 },
  { glob: 'packages/client/runtime/src/client/conversation/event-registry.ts', lines: 100, statements: 95.65, branches: 87.5, functions: 100 },
  { glob: 'packages/client/runtime/src/client/index.ts', lines: 86.36, statements: 88, branches: 50, functions: 75 },
  { glob: 'packages/client/runtime/src/client/sessions/assistant-timing.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/runtime/src/client/sessions/conversation-assembler.ts', lines: 95.12, statements: 93.45, branches: 87, functions: 98.03 },
  { glob: 'packages/client/runtime/src/client/sessions/conversation-location-index.ts', lines: 96.21, statements: 94.46, branches: 89.8, functions: 100 },
  { glob: 'packages/client/runtime/src/client/sessions/conversation.ts', lines: 68.75, statements: 68.75, branches: 80, functions: 42.85 },
  { glob: 'packages/client/runtime/src/client/sessions/failure-display.ts', lines: 100, statements: 66.66, branches: 62.5, functions: 100 },
  { glob: 'packages/client/runtime/src/client/sessions/manager.ts', lines: 98.3, statements: 97.1, branches: 90.86, functions: 100 },
  { glob: 'packages/client/runtime/src/client/sessions/partial.ts', lines: 97.29, statements: 97.36, branches: 82.14, functions: 83.33 },
  { glob: 'packages/client/runtime/src/client/sessions/provide.ts', lines: 95.38, statements: 95.94, branches: 83.33, functions: 100 },
  { glob: 'packages/client/runtime/src/client/sessions/service.ts', lines: 94.37, statements: 92.61, branches: 92.17, functions: 90.9 },
  { glob: 'packages/client/runtime/src/client/sessions/session.ts', lines: 97.79, statements: 96.21, branches: 93.6, functions: 96.22 },
  { glob: 'packages/client/runtime/src/client/sessions/steering-history.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/runtime/src/client/sessions/tool-call-tree.ts', lines: 79.22, statements: 79.12, branches: 71.01, functions: 64.28 },
  { glob: 'packages/client/runtime/src/client/slots.ts', lines: 96.85, statements: 95.23, branches: 88.23, functions: 90.69 },
  { glob: 'packages/client/runtime/src/client/workspaces/manager.ts', lines: 90.79, statements: 88.2, branches: 72.03, functions: 83.72 },
  { glob: 'packages/client/runtime/src/client/workspaces/service.ts', lines: 93.04, statements: 90.37, branches: 87.83, functions: 87.5 },
  { glob: 'packages/client/runtime/src/client/workspaces/workspace.ts', lines: 94.59, statements: 87.8, branches: 66.66, functions: 90 },
  { glob: 'packages/client/ui-commands/src/client/PopupSelectView.tsx', lines: 100, statements: 100, branches: 97.87, functions: 100 },
  { glob: 'packages/client/ui-commands/src/client/directory.ts', lines: 100, statements: 100, branches: 93.75, functions: 100 },
  { glob: 'packages/client/ui-commands/src/client/popup.ts', lines: 100, statements: 95.91, branches: 93.97, functions: 100 },
  { glob: 'packages/client/ui-commands/src/client/service.ts', lines: 98.36, statements: 95.27, branches: 89.13, functions: 94.11 },
  { glob: 'packages/client/ui-commands/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/client/ui-conversation/src/client/apply.ts', lines: 77.44, statements: 75.69, branches: 56, functions: 71.18 },
  { glob: 'packages/client/ui-conversation/src/client/chat/AssistantMarkdown.tsx', lines: 96.55, statements: 91.42, branches: 91.66, functions: 60 },
  { glob: 'packages/client/ui-conversation/src/client/chat/AssistantNodeView.tsx', lines: 100, statements: 100, branches: 83.33, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/chat/ChatNodeSeat.tsx', lines: 87.5, statements: 81.81, branches: 66.66, functions: 75 },
  { glob: 'packages/client/ui-conversation/src/client/chat/ChatView.tsx', lines: 93.78, statements: 93.8, branches: 87.8, functions: 97.72 },
  { glob: 'packages/client/ui-conversation/src/client/chat/CompactionCommandCard.tsx', lines: 100, statements: 80, branches: 66.66, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/chat/CompactionItem.tsx', lines: 100, statements: 100, branches: 95.23, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/chat/ContextBody.tsx', lines: 97.6, statements: 90.54, branches: 85.29, functions: 91.17 },
  { glob: 'packages/client/ui-conversation/src/client/chat/GenericCommandCard.tsx', lines: 91.66, statements: 85.71, branches: 93.33, functions: 60 },
  { glob: 'packages/client/ui-conversation/src/client/chat/MessageIconActions.tsx', lines: 100, statements: 100, branches: 97.91, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/chat/MessageItem.tsx', lines: 87.5, statements: 84.52, branches: 72.72, functions: 89.28 },
  { glob: 'packages/client/ui-conversation/src/client/chat/ReasoningRow.tsx', lines: 100, statements: 94.44, branches: 93.75, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/chat/StatsLine.tsx', lines: 100, statements: 98.68, branches: 97.87, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/chat/TurnTailNodeView.tsx', lines: 100, statements: 88.23, branches: 60, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/chat/turn-assistant.ts', lines: 100, statements: 100, branches: 50, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/contract/decorations.ts', lines: 100, statements: 100, branches: 90.9, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/contract/slots.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/ui-conversation/src/client/contract/tool-node-reader.ts', lines: 92.85, statements: 88.88, branches: 80, functions: 75 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/assistant.ts', lines: 84, statements: 83.76, branches: 79.57, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/chat-snapshot-builder.ts', lines: 98.43, statements: 95.9, branches: 86.71, functions: 93.33 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/command.ts', lines: 100, statements: 94.44, branches: 84.37, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/common.ts', lines: 75, statements: 75, branches: 53.84, functions: 66.66 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/compaction.ts', lines: 100, statements: 96, branches: 92, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/fallback.ts', lines: 50, statements: 50, branches: 25, functions: 40 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/inbox.ts', lines: 94.44, statements: 90.47, branches: 87.5, functions: 85.71 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/message.ts', lines: 80, statements: 72.22, branches: 73.68, functions: 83.33 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/retry.ts', lines: 100, statements: 89.47, branches: 78.72, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/tool.ts', lines: 97.97, statements: 88.03, branches: 78.62, functions: 95.65 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/turn-error.ts', lines: 100, statements: 93.02, branches: 86.95, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/turn-max-tokens.ts', lines: 100, statements: 92.59, branches: 80, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/conversation-nodes/turn-tail.ts', lines: 89.33, statements: 86.36, branches: 79.61, functions: 90.9 },
  { glob: 'packages/client/ui-conversation/src/client/input/blocks.ts', lines: 54.54, statements: 46.15, branches: 25, functions: 33.33 },
  { glob: 'packages/client/ui-conversation/src/client/input/facade.ts', lines: 75.64, statements: 69.44, branches: 58.62, functions: 77.19 },
  { glob: 'packages/client/ui-conversation/src/client/input/hub.ts', lines: 84.84, statements: 81.48, branches: 60.52, functions: 70.83 },
  { glob: 'packages/client/ui-conversation/src/client/input/machine.ts', lines: 98.08, statements: 96.28, branches: 91.14, functions: 94.44 },
  { glob: 'packages/client/ui-conversation/src/client/queue/QueueDock.tsx', lines: 94.11, statements: 89.39, branches: 88.7, functions: 88 },
  { glob: 'packages/client/ui-conversation/src/client/service.ts', lines: 86.11, statements: 77.69, branches: 67.18, functions: 86.2 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/ApprovalPanel.tsx', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/ContextMeter.tsx', lines: 100, statements: 100, branches: 96.66, functions: 100 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/ConversationRoot.tsx', lines: 93.87, statements: 95.16, branches: 93.97, functions: 90.9 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/ConversationSession.tsx', lines: 98.03, statements: 97.1, branches: 97.77, functions: 96.15 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/DetailsPanel.tsx', lines: 90, statements: 88.46, branches: 97.14, functions: 91.66 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/EmptyHero.tsx', lines: 66.66, statements: 66.66, branches: 71.42, functions: 75 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/InputBar.tsx', lines: 89.96, statements: 85.09, branches: 83.01, functions: 91.54 },
  { glob: 'packages/client/ui-conversation/src/client/skeleton/PermissionSelect.tsx', lines: 95.83, statements: 90.9, branches: 82.85, functions: 88.23 },
  { glob: 'packages/client/ui-input-trigger/src/client/controller.ts', lines: 94.33, statements: 92.67, branches: 92.85, functions: 92.85 },
  { glob: 'packages/client/ui-input-trigger/src/client/service.ts', lines: 96.96, statements: 95.23, branches: 93.75, functions: 100 },
  { glob: 'packages/client/ui-input-trigger/src/core/detect.ts', lines: 100, statements: 100, branches: 96.77, functions: 100 },
  { glob: 'packages/client/ui-input-trigger/src/core/menu.ts', lines: 100, statements: 98.7, branches: 98.73, functions: 100 },
  { glob: 'packages/client/ui-input-trigger/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/client/ui-model-selection/src/client/ModelSelect.tsx', lines: 78.18, statements: 75, branches: 68.25, functions: 78.94 },
  { glob: 'packages/client/ui-model-selection/src/client/directory.ts', lines: 85.18, statements: 77.27, branches: 62.5, functions: 78.57 },
  { glob: 'packages/client/ui-model-selection/src/client/index.ts', lines: 91.3, statements: 90.56, branches: 73.07, functions: 89.47 },
  { glob: 'packages/client/ui-model-selection/src/client/service.ts', lines: 100, statements: 97.5, branches: 87.5, functions: 90 },
  { glob: 'packages/client/ui-model-selection/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/client/ui-permission-presets/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/client/ui-primitives/src/DisclosureRow.tsx', lines: 81.81, statements: 83.33, branches: 97.29, functions: 66.66 },
  { glob: 'packages/client/ui-primitives/src/JsonTree.tsx', lines: 100, statements: 100, branches: 99.45, functions: 100 },
  { glob: 'packages/client/ui-primitives/src/Menu.tsx', lines: 97.43, statements: 96.66, branches: 94.91, functions: 100 },
  { glob: 'packages/client/ui-primitives/src/RiskConfirmation.tsx', lines: 100, statements: 100, branches: 71.42, functions: 100 },
  { glob: 'packages/client/ui-primitives/src/markdown/plain-text.ts', lines: 97.14, statements: 97.36, branches: 75.8, functions: 100 },
  { glob: 'packages/client/ui-settings-models/src/client/DeepSeekOnboardingDialog.tsx', lines: 95, statements: 95.45, branches: 94.11, functions: 100 },
  { glob: 'packages/client/ui-settings-models/src/client/welcome-store.ts', lines: 100, statements: 100, branches: 96.55, functions: 100 },
  { glob: 'packages/client/ui-skill/src/client/index.ts', lines: 98.36, statements: 97.22, branches: 85, functions: 95.45 },
  { glob: 'packages/client/ui-skill/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/client/ui-slots/src/index.ts', lines: 88.12, statements: 86.84, branches: 77.91, functions: 82.5 },
  { glob: 'packages/client/ui-subagent/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/client/ui-tool/src/client/tool/ToolCallTree.tsx', lines: 90, statements: 90.9, branches: 100, functions: 85.71 },
  { glob: 'packages/client/ui-tool/src/client/tool/ToolDetails.tsx', lines: 100, statements: 100, branches: 90.9, functions: 100 },
  { glob: 'packages/client/ui-tool/src/client/tool/components/ToolRow.tsx', lines: 96.96, statements: 94.44, branches: 94.38, functions: 85.71 },
  { glob: 'packages/client/ui-tool/src/client/tool/models/terminal-card-model.ts', lines: 94.87, statements: 95.65, branches: 96.66, functions: 80 },
  { glob: 'packages/client/ui-tool/src/client/tool/toolviews/bash-sample.tsx', lines: 90, statements: 87.87, branches: 90.47, functions: 88.88 },
  { glob: 'packages/client/ui-tool/src/client/tool/toolviews/search-row.tsx', lines: 100, statements: 100, branches: 75, functions: 100 },
  { glob: 'packages/client/ui-tool/src/client/tool/toolviews/web-row.tsx', lines: 100, statements: 100, branches: 75, functions: 100 },
  { glob: 'packages/client/ui-tool/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/client/ui-trajectory/src/client/TrajectoryTable.tsx', lines: 66.34, statements: 63, branches: 62.31, functions: 63.59 },
  { glob: 'packages/client/ui-trajectory/src/client/TrajectoryTimeline.tsx', lines: 85.23, statements: 82.37, branches: 77.37, functions: 81.13 },
  { glob: 'packages/client/ui-trajectory/src/client/TrajectoryToolbar.tsx', lines: 50, statements: 50, branches: 81.25, functions: 50 },
  { glob: 'packages/client/ui-trajectory/src/client/TrajectoryView.tsx', lines: 75.93, statements: 74.88, branches: 47.15, functions: 70.49 },
  { glob: 'packages/client/ui-trajectory/src/client/index.ts', lines: 95, statements: 95.45, branches: 50, functions: 100 },
  { glob: 'packages/client/ui-trajectory/src/client/layout.ts', lines: 83.87, statements: 80.88, branches: 62.05, functions: 85.55 },
  { glob: 'packages/client/ui-trajectory/src/client/timeline.ts', lines: 100, statements: 93.93, branches: 78.84, functions: 100 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-assistant-definition.ts', lines: 66.66, statements: 65.21, branches: 62.08, functions: 82.6 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-compaction-definition.ts', lines: 94.28, statements: 90, branches: 80.32, functions: 91.66 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-definition-common.ts', lines: 100, statements: 100, branches: 50, functions: 100 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-message-definitions.ts', lines: 85.18, statements: 86.2, branches: 75, functions: 80 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-preview.ts', lines: 100, statements: 100, branches: 75, functions: 100 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-request-header-definition.ts', lines: 90, statements: 78.26, branches: 45.94, functions: 85.71 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-search-index.ts', lines: 81.08, statements: 72.34, branches: 75.86, functions: 70 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-snapshot-builder.ts', lines: 99.16, statements: 93.61, branches: 83.69, functions: 100 },
  { glob: 'packages/client/ui-trajectory/src/client/trajectory-tool-definition.ts', lines: 78.49, statements: 69.02, branches: 54.62, functions: 83.33 },
  { glob: 'packages/client/ui-user-questions/src/client/QuestionComposer.tsx', lines: 97.64, statements: 98.05, branches: 98.03, functions: 100 },
  { glob: 'packages/client/ui-workspace/src/client/WorkspaceBrowser.tsx', lines: 94.36, statements: 91.14, branches: 85.16, functions: 91.22 },
  { glob: 'packages/client/ui-workspace/src/client/index.ts', lines: 90.32, statements: 90, branches: 83.33, functions: 82.6 },
  { glob: 'packages/client/web-react/src/scoped-slots.tsx', lines: 97.54, statements: 96.2, branches: 89.11, functions: 96.36 },
  { glob: 'packages/client/web-react/src/session-provider.tsx', lines: 92.5, statements: 89.79, branches: 85, functions: 93.75 },
  { glob: 'packages/client/web-react/src/use-invoke.ts', lines: 100, statements: 95.23, branches: 100, functions: 88.88 },
  { glob: 'packages/client/web/src/boot.tsx', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/client/web/src/seed.ts', lines: 0, statements: 0, branches: 100, functions: 0 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/api-catalog.ts', lines: 12.9, statements: 10.25, branches: 0, functions: 0 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/guard.ts', lines: 96.2, statements: 95.83, branches: 91.17, functions: 100 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/index.ts', lines: 85.91, statements: 77.64, branches: 56.25, functions: 73.52 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/inspect-registry.ts', lines: 61.7, statements: 55.35, branches: 26.92, functions: 66.66 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/orchestrator.ts', lines: 71.42, statements: 70.42, branches: 53.33, functions: 84.61 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/providers.ts', lines: 31.81, statements: 30, branches: 4, functions: 21.05 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/runtime.ts', lines: 99.02, statements: 99.12, branches: 91.48, functions: 97.36 },
  { glob: 'packages/extensions/cordis-client-runner/src/client/timer.ts', lines: 4.34, statements: 3.79, branches: 0, functions: 6.89 },
  { glob: 'packages/extensions/cordis-host-runner/src/guard.ts', lines: 74.57, statements: 70.93, branches: 61.88, functions: 90.74 },
  { glob: 'packages/extensions/cordis-host-runner/src/index.ts', lines: 80.96, statements: 78.75, branches: 70.76, functions: 81.53 },
  { glob: 'packages/extensions/cordis-host-runner/src/inspect-registry.ts', lines: 25.58, statements: 21.49, branches: 14.58, functions: 23.8 },
  { glob: 'packages/extensions/cordis-host-runner/src/registry.ts', lines: 96, statements: 96.55, branches: 50, functions: 93.33 },
  { glob: 'packages/extensions/cordis-host-runner/src/sandbox.ts', lines: 100, statements: 97.72, branches: 93.75, functions: 100 },
  { glob: 'packages/extensions/tool-cordis/src/api-catalog.ts', lines: 12.9, statements: 10.25, branches: 0, functions: 0 },
  { glob: 'packages/extensions/tool-cordis/src/index.ts', lines: 12.03, statements: 10.85, branches: 0, functions: 5.71 },
  { glob: 'packages/extensions/tool-cordis/src/inspect.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/extensions/tool-cordis/src/present.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/extensions/tool-cordis/src/providers.ts', lines: 50, statements: 45.83, branches: 14.28, functions: 40 },
  { glob: 'packages/extensions/ui-cordis/src/client/CordisActionRow.tsx', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/extensions/ui-cordis/src/client/CordisDefineRow.tsx', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/extensions/ui-cordis/src/client/CordisPanel.tsx', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/extensions/ui-cordis/src/client/CordisRunRow.tsx', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/extensions/ui-cordis/src/client/card-model.ts', lines: 100, statements: 100, branches: 84.9, functions: 100 },
  { glob: 'packages/extensions/ui-cordis/src/client/index.ts', lines: 0, statements: 0, branches: 0, functions: 0 },
  { glob: 'packages/extensions/ui-cordis/src/client/inventory.ts', lines: 89.65, statements: 86.84, branches: 91.66, functions: 84.61 },
  { glob: 'packages/extensions/ui-cordis/src/client/locales.ts', lines: 0, statements: 0, branches: 100, functions: 100 },
  { glob: 'packages/extensions/ui-cordis/src/client/run-card-index.ts', lines: 100, statements: 95.23, branches: 83.33, functions: 85.71 },
  { glob: 'packages/extensions/ui-cordis/src/client/status.ts', lines: 100, statements: 90, branches: 90.9, functions: 100 },
  { glob: 'packages/extensions/ui-cordis/src/index.ts', lines: 100, statements: 100, branches: 100, functions: 0 },
  { glob: 'packages/host/apiproxy/src/api-proxy.ts', lines: 89.62, statements: 87.23, branches: 78.65, functions: 89.78 },
  { glob: 'packages/host/apiproxy/src/index.ts', lines: 10, statements: 10, branches: 0, functions: 0 },
  { glob: 'packages/host/webserver/src/index.ts', lines: 88.04, statements: 88.57, branches: 69.44, functions: 93.54 },
  { glob: 'packages/host/webserver/src/invariant.ts', lines: 94.11, statements: 94.44, branches: 100, functions: 60 },
  { glob: 'packages/interaction/commands/src/index.ts', lines: 98.98, statements: 99.08, branches: 98.75, functions: 100 },
  { glob: 'packages/interaction/commands/src/invariant.ts', lines: 92.85, statements: 93.54, branches: 91.66, functions: 100 },
  { glob: 'packages/session/session-projection/src/index.ts', lines: 100, statements: 98.88, branches: 100, functions: 94.44 },
  { glob: 'packages/test-support/client-runtime/src/translate.ts', lines: 100, statements: 100, branches: 83.33, functions: 100 },
  { glob: 'packages/workflow/tool-workflow/src/index.ts', lines: 100, statements: 98.75, branches: 97.43, functions: 100 },
]

/** Coverage-relative globs of every debt file (for the debt-lane include and the main exclude). */
export const coverageDebtGlobs: readonly string[] = coverageDebt.map(e => e.glob)
